name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Install GeckoDriver
        run: |
          curl -L "https://github.com/mozilla/geckodriver/releases/latest/download/geckodriver-v0.34.0-win64.zip" -o geckodriver.zip
          tar -xf geckodriver.zip
          move geckodriver.exe "C:\\Program Files\\GeckoDriver\\"
          echo "C:\\Program Files\\GeckoDriver" >> $GITHUB_PATH

      - name: Run tests in parallel
        run: |
          python -m pytest --maxfail=5 --disable-warnings -n auto --capture=tee-sys
