name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extension-csv: mbstring, pdo_mysql

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Copy geckodriver to PATH
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path "C:\Program Files\GeckoDriver" -Force | Out-Null
          Copy-Item webdriver\geckodriver.exe "C:\Program Files\GeckoDriver\"
          echo "C:\Program Files\GeckoDriver" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Start local PHP server
        shell: pwsh
        run: |
          Start-Process php -ArgumentList '-S 127.0.0.1:8000 -t .' -NoNewWindow
          Start-Sleep -Seconds 5

      - name: Run tests
        shell: pwsh
        run: |
          python -m pytest test_integration.py -v
